const REGIONS = [
  { id: "all",       name: "전체",     emoji: "🌐" },
  { id: "asia",      name: "아시아",   emoji: "🌏" },
  { id: "europe",    name: "유럽",     emoji: "🌍" },
  { id: "americas",  name: "아메리카", emoji: "🌎" },
  { id: "africa",    name: "아프리카", emoji: "🌍" },
  { id: "middleeast",name: "중동",     emoji: "🕌" },
  { id: "oceania",   name: "오세아니아", emoji: "🌊" },
];

const COUNTRIES = [
  // ── 아시아 ──────────────────────────────────────────────
  { code: "AF", name: "아프가니스탄",     capital: "카불",              region: "asia" },
  { code: "AM", name: "아르메니아",       capital: "예레반",            region: "asia" },
  { code: "AZ", name: "아제르바이잔",     capital: "바쿠",              region: "asia" },
  { code: "BH", name: "바레인",           capital: "마나마",            region: "middleeast" },
  { code: "BD", name: "방글라데시",       capital: "다카",              region: "asia" },
  { code: "BT", name: "부탄",             capital: "팀부",              region: "asia" },
  { code: "BN", name: "브루나이",         capital: "반다르스리브가완",  region: "asia" },
  { code: "KH", name: "캄보디아",         capital: "프놈펜",            region: "asia" },
  { code: "CN", name: "중국",             capital: "베이징",            region: "asia" },
  { code: "TL", name: "동티모르",         capital: "딜리",              region: "asia" },
  { code: "GE", name: "조지아",           capital: "트빌리시",          region: "asia" },
  { code: "IN", name: "인도",             capital: "뉴델리",            region: "asia" },
  { code: "ID", name: "인도네시아",       capital: "자카르타",          region: "asia" },
  { code: "IR", name: "이란",             capital: "테헤란",            region: "middleeast" },
  { code: "IQ", name: "이라크",           capital: "바그다드",          region: "middleeast" },
  { code: "IL", name: "이스라엘",         capital: "예루살렘",          region: "middleeast" },
  { code: "JP", name: "일본",             capital: "도쿄",              region: "asia" },
  { code: "JO", name: "요르단",           capital: "암만",              region: "middleeast" },
  { code: "KZ", name: "카자흐스탄",       capital: "아스타나",          region: "asia" },
  { code: "KP", name: "북한",             capital: "평양",              region: "asia" },
  { code: "KR", name: "대한민국",         capital: "서울",              region: "asia" },
  { code: "KW", name: "쿠웨이트",         capital: "쿠웨이트시티",      region: "middleeast" },
  { code: "KG", name: "키르기스스탄",     capital: "비슈케크",          region: "asia" },
  { code: "LA", name: "라오스",           capital: "비엔티안",          region: "asia" },
  { code: "LB", name: "레바논",           capital: "베이루트",          region: "middleeast" },
  { code: "MY", name: "말레이시아",       capital: "쿠알라룸푸르",      region: "asia" },
  { code: "MV", name: "몰디브",           capital: "말레",              region: "asia" },
  { code: "MN", name: "몽골",             capital: "울란바토르",        region: "asia" },
  { code: "MM", name: "미얀마",           capital: "네피도",            region: "asia" },
  { code: "NP", name: "네팔",             capital: "카트만두",          region: "asia" },
  { code: "OM", name: "오만",             capital: "무스카트",          region: "middleeast" },
  { code: "PK", name: "파키스탄",         capital: "이슬라마바드",      region: "asia" },
  { code: "PH", name: "필리핀",           capital: "마닐라",            region: "asia" },
  { code: "QA", name: "카타르",           capital: "도하",              region: "middleeast" },
  { code: "SA", name: "사우디아라비아",   capital: "리야드",            region: "middleeast" },
  { code: "SG", name: "싱가포르",         capital: "싱가포르",          region: "asia" },
  { code: "LK", name: "스리랑카",         capital: "스리자야와르데네푸라코테", region: "asia" },
  { code: "SY", name: "시리아",           capital: "다마스쿠스",        region: "middleeast" },
  { code: "TW", name: "대만",             capital: "타이베이",          region: "asia" },
  { code: "TJ", name: "타지키스탄",       capital: "두샨베",            region: "asia" },
  { code: "TH", name: "태국",             capital: "방콕",              region: "asia" },
  { code: "TR", name: "튀르키예",         capital: "앙카라",            region: "middleeast" },
  { code: "TM", name: "투르크메니스탄",   capital: "아슈하바트",        region: "asia" },
  { code: "AE", name: "아랍에미리트",     capital: "아부다비",          region: "middleeast" },
  { code: "UZ", name: "우즈베키스탄",     capital: "타슈켄트",          region: "asia" },
  { code: "VN", name: "베트남",           capital: "하노이",            region: "asia" },
  { code: "YE", name: "예멘",             capital: "사나",              region: "middleeast" },

  // ── 유럽 ──────────────────────────────────────────────
  { code: "AL", name: "알바니아",         capital: "티라나",            region: "europe" },
  { code: "AD", name: "안도라",           capital: "안도라라베야",      region: "europe" },
  { code: "AT", name: "오스트리아",       capital: "빈",                region: "europe" },
  { code: "BY", name: "벨라루스",         capital: "민스크",            region: "europe" },
  { code: "BE", name: "벨기에",           capital: "브뤼셀",            region: "europe" },
  { code: "BA", name: "보스니아 헤르체고비나", capital: "사라예보",     region: "europe" },
  { code: "BG", name: "불가리아",         capital: "소피아",            region: "europe" },
  { code: "HR", name: "크로아티아",       capital: "자그레브",          region: "europe" },
  { code: "CY", name: "키프로스",         capital: "니코시아",          region: "europe" },
  { code: "CZ", name: "체코",             capital: "프라하",            region: "europe" },
  { code: "DK", name: "덴마크",           capital: "코펜하겐",          region: "europe" },
  { code: "EE", name: "에스토니아",       capital: "탈린",              region: "europe" },
  { code: "FI", name: "핀란드",           capital: "헬싱키",            region: "europe" },
  { code: "FR", name: "프랑스",           capital: "파리",              region: "europe" },
  { code: "DE", name: "독일",             capital: "베를린",            region: "europe" },
  { code: "GR", name: "그리스",           capital: "아테네",            region: "europe" },
  { code: "HU", name: "헝가리",           capital: "부다페스트",        region: "europe" },
  { code: "IS", name: "아이슬란드",       capital: "레이캬비크",        region: "europe" },
  { code: "IE", name: "아일랜드",         capital: "더블린",            region: "europe" },
  { code: "IT", name: "이탈리아",         capital: "로마",              region: "europe" },
  { code: "LV", name: "라트비아",         capital: "리가",              region: "europe" },
  { code: "LI", name: "리히텐슈타인",     capital: "파두츠",            region: "europe" },
  { code: "LT", name: "리투아니아",       capital: "빌뉴스",            region: "europe" },
  { code: "LU", name: "룩셈부르크",       capital: "룩셈부르크",        region: "europe" },
  { code: "MT", name: "몰타",             capital: "발레타",            region: "europe" },
  { code: "MD", name: "몰도바",           capital: "키시나우",          region: "europe" },
  { code: "MC", name: "모나코",           capital: "모나코",            region: "europe" },
  { code: "ME", name: "몬테네그로",       capital: "포드고리차",        region: "europe" },
  { code: "NL", name: "네덜란드",         capital: "암스테르담",        region: "europe" },
  { code: "MK", name: "북마케도니아",     capital: "스코페",            region: "europe" },
  { code: "NO", name: "노르웨이",         capital: "오슬로",            region: "europe" },
  { code: "PL", name: "폴란드",           capital: "바르샤바",          region: "europe" },
  { code: "PT", name: "포르투갈",         capital: "리스본",            region: "europe" },
  { code: "RO", name: "루마니아",         capital: "부쿠레슈티",        region: "europe" },
  { code: "RU", name: "러시아",           capital: "모스크바",          region: "europe" },
  { code: "SM", name: "산마리노",         capital: "산마리노",          region: "europe" },
  { code: "RS", name: "세르비아",         capital: "베오그라드",        region: "europe" },
  { code: "SK", name: "슬로바키아",       capital: "브라티슬라바",      region: "europe" },
  { code: "SI", name: "슬로베니아",       capital: "류블랴나",          region: "europe" },
  { code: "ES", name: "스페인",           capital: "마드리드",          region: "europe" },
  { code: "SE", name: "스웨덴",           capital: "스톡홀름",          region: "europe" },
  { code: "CH", name: "스위스",           capital: "베른",              region: "europe" },
  { code: "UA", name: "우크라이나",       capital: "키이우",            region: "europe" },
  { code: "GB", name: "영국",             capital: "런던",              region: "europe" },

  // ── 아메리카 ──────────────────────────────────────────────
  { code: "AG", name: "앤티가 바부다",     capital: "세인트존스",        region: "americas" },
  { code: "AR", name: "아르헨티나",       capital: "부에노스아이레스",  region: "americas" },
  { code: "BS", name: "바하마",           capital: "나소",              region: "americas" },
  { code: "BB", name: "바베이도스",       capital: "브리지타운",        region: "americas" },
  { code: "BZ", name: "벨리즈",           capital: "벨모판",            region: "americas" },
  { code: "BO", name: "볼리비아",         capital: "수크레",            region: "americas" },
  { code: "BR", name: "브라질",           capital: "브라질리아",        region: "americas" },
  { code: "CA", name: "캐나다",           capital: "오타와",            region: "americas" },
  { code: "CL", name: "칠레",             capital: "산티아고",          region: "americas" },
  { code: "CO", name: "콜롬비아",         capital: "보고타",            region: "americas" },
  { code: "CR", name: "코스타리카",       capital: "산호세",            region: "americas" },
  { code: "CU", name: "쿠바",             capital: "아바나",            region: "americas" },
  { code: "DM", name: "도미니카",         capital: "로조",              region: "americas" },
  { code: "DO", name: "도미니카 공화국",  capital: "산토도밍고",        region: "americas" },
  { code: "EC", name: "에콰도르",         capital: "키토",              region: "americas" },
  { code: "SV", name: "엘살바도르",       capital: "산살바도르",        region: "americas" },
  { code: "GD", name: "그레나다",         capital: "세인트조지스",      region: "americas" },
  { code: "GT", name: "과테말라",         capital: "과테말라시티",      region: "americas" },
  { code: "GY", name: "가이아나",         capital: "조지타운",          region: "americas" },
  { code: "HT", name: "아이티",           capital: "포르토프랭스",      region: "americas" },
  { code: "HN", name: "온두라스",         capital: "테구시갈파",        region: "americas" },
  { code: "JM", name: "자메이카",         capital: "킹스턴",            region: "americas" },
  { code: "MX", name: "멕시코",           capital: "멕시코시티",        region: "americas" },
  { code: "NI", name: "니카라과",         capital: "마나과",            region: "americas" },
  { code: "PA", name: "파나마",           capital: "파나마시티",        region: "americas" },
  { code: "PY", name: "파라과이",         capital: "아순시온",          region: "americas" },
  { code: "PE", name: "페루",             capital: "리마",              region: "americas" },
  { code: "KN", name: "세인트키츠 네비스", capital: "바스테르",         region: "americas" },
  { code: "LC", name: "세인트루시아",     capital: "캐스트리스",        region: "americas" },
  { code: "VC", name: "세인트빈센트 그레나딘", capital: "킹스타운",     region: "americas" },
  { code: "SR", name: "수리남",           capital: "파라마리보",        region: "americas" },
  { code: "TT", name: "트리니다드 토바고", capital: "포트오브스페인",   region: "americas" },
  { code: "US", name: "미국",             capital: "워싱턴 D.C.",       region: "americas" },
  { code: "UY", name: "우루과이",         capital: "몬테비데오",        region: "americas" },
  { code: "VE", name: "베네수엘라",       capital: "카라카스",          region: "americas" },

  // ── 아프리카 ──────────────────────────────────────────────
  { code: "DZ", name: "알제리",           capital: "알제",              region: "africa" },
  { code: "AO", name: "앙골라",           capital: "루안다",            region: "africa" },
  { code: "BJ", name: "베냉",             capital: "포르토노보",        region: "africa" },
  { code: "BW", name: "보츠와나",         capital: "가보로네",          region: "africa" },
  { code: "BF", name: "부르키나파소",     capital: "와가두구",          region: "africa" },
  { code: "BI", name: "부룬디",           capital: "기테가",            region: "africa" },
  { code: "CV", name: "카보베르데",       capital: "프라이아",          region: "africa" },
  { code: "CM", name: "카메룬",           capital: "야운데",            region: "africa" },
  { code: "CF", name: "중앙아프리카공화국", capital: "방기",            region: "africa" },
  { code: "TD", name: "차드",             capital: "은자메나",          region: "africa" },
  { code: "KM", name: "코모로",           capital: "모로니",            region: "africa" },
  { code: "CG", name: "콩고 공화국",      capital: "브라자빌",          region: "africa" },
  { code: "CD", name: "콩고 민주 공화국", capital: "킨샤사",            region: "africa" },
  { code: "DJ", name: "지부티",           capital: "지부티",            region: "africa" },
  { code: "EG", name: "이집트",           capital: "카이로",            region: "africa" },
  { code: "GQ", name: "적도 기니",        capital: "말라보",            region: "africa" },
  { code: "ER", name: "에리트레아",       capital: "아스마라",          region: "africa" },
  { code: "SZ", name: "에스와티니",       capital: "음바바네",          region: "africa" },
  { code: "ET", name: "에티오피아",       capital: "아디스아바바",      region: "africa" },
  { code: "GA", name: "가봉",             capital: "리브르빌",          region: "africa" },
  { code: "GM", name: "감비아",           capital: "반줄",              region: "africa" },
  { code: "GH", name: "가나",             capital: "아크라",            region: "africa" },
  { code: "GN", name: "기니",             capital: "코나크리",          region: "africa" },
  { code: "GW", name: "기니비사우",       capital: "비사우",            region: "africa" },
  { code: "CI", name: "코트디부아르",     capital: "야무수크로",        region: "africa" },
  { code: "KE", name: "케냐",             capital: "나이로비",          region: "africa" },
  { code: "LS", name: "레소토",           capital: "마세루",            region: "africa" },
  { code: "LR", name: "라이베리아",       capital: "몬로비아",          region: "africa" },
  { code: "LY", name: "리비아",           capital: "트리폴리",          region: "africa" },
  { code: "MG", name: "마다가스카르",     capital: "안타나나리보",      region: "africa" },
  { code: "MW", name: "말라위",           capital: "릴롱궤",            region: "africa" },
  { code: "ML", name: "말리",             capital: "바마코",            region: "africa" },
  { code: "MR", name: "모리타니",         capital: "누악쇼트",          region: "africa" },
  { code: "MU", name: "모리셔스",         capital: "포트루이스",        region: "africa" },
  { code: "MA", name: "모로코",           capital: "라바트",            region: "africa" },
  { code: "MZ", name: "모잠비크",         capital: "마푸투",            region: "africa" },
  { code: "NA", name: "나미비아",         capital: "빈트후크",          region: "africa" },
  { code: "NE", name: "니제르",           capital: "니아메",            region: "africa" },
  { code: "NG", name: "나이지리아",       capital: "아부자",            region: "africa" },
  { code: "RW", name: "르완다",           capital: "키갈리",            region: "africa" },
  { code: "ST", name: "상투메 프린시페",  capital: "상투메",            region: "africa" },
  { code: "SN", name: "세네갈",           capital: "다카르",            region: "africa" },
  { code: "SC", name: "세이셸",           capital: "빅토리아",          region: "africa" },
  { code: "SL", name: "시에라리온",       capital: "프리타운",          region: "africa" },
  { code: "SO", name: "소말리아",         capital: "모가디슈",          region: "africa" },
  { code: "ZA", name: "남아프리카 공화국", capital: "프리토리아",       region: "africa" },
  { code: "SS", name: "남수단",           capital: "주바",              region: "africa" },
  { code: "SD", name: "수단",             capital: "하르툼",            region: "africa" },
  { code: "TZ", name: "탄자니아",         capital: "도도마",            region: "africa" },
  { code: "TG", name: "토고",             capital: "로메",              region: "africa" },
  { code: "TN", name: "튀니지",           capital: "튀니스",            region: "africa" },
  { code: "UG", name: "우간다",           capital: "캄팔라",            region: "africa" },
  { code: "ZM", name: "잠비아",           capital: "루사카",            region: "africa" },
  { code: "ZW", name: "짐바브웨",         capital: "하라레",            region: "africa" },
  { code: "KM", name: "코모로",           capital: "모로니",            region: "africa" },

  // ── 오세아니아 ──────────────────────────────────────────────
  { code: "AU", name: "오스트레일리아",   capital: "캔버라",            region: "oceania" },
  { code: "FJ", name: "피지",             capital: "수바",              region: "oceania" },
  { code: "KI", name: "키리바시",         capital: "타라와",            region: "oceania" },
  { code: "MH", name: "마셜 제도",        capital: "마주로",            region: "oceania" },
  { code: "FM", name: "미크로네시아",     capital: "팔리키르",          region: "oceania" },
  { code: "NR", name: "나우루",           capital: "야렌",              region: "oceania" },
  { code: "NZ", name: "뉴질랜드",         capital: "웰링턴",            region: "oceania" },
  { code: "PW", name: "팔라우",           capital: "응에룰무드",        region: "oceania" },
  { code: "PG", name: "파푸아뉴기니",     capital: "포트모르즈비",      region: "oceania" },
  { code: "WS", name: "사모아",           capital: "아피아",            region: "oceania" },
  { code: "SB", name: "솔로몬 제도",      capital: "호니아라",          region: "oceania" },
  { code: "TO", name: "통가",             capital: "누쿠알로파",        region: "oceania" },
  { code: "TV", name: "투발루",           capital: "푸나푸티",          region: "oceania" },
  { code: "VU", name: "바누아투",         capital: "포트빌라",          region: "oceania" },
];

// 중복 제거 (코모로 등)
const seen = new Set();
const COUNTRIES_UNIQUE = COUNTRIES.filter(c => {
  if (seen.has(c.code)) return false;
  seen.add(c.code);
  return true;
});
// COUNTRIES_UNIQUE를 실제로 사용
COUNTRIES.length = 0;
COUNTRIES_UNIQUE.forEach(c => COUNTRIES.push(c));
